//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delicious
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public int DishId { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
