//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delicious
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RestaurantPlaceId { get; set; }
        public string BookDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual RestaurantsPlaces RestaurantsPlaces { get; set; }
    }
}
