//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delicious
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantsPlaces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantsPlaces()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public int PlaceId { get; set; }
        public int PlaceCount { get; set; }
        public int CurrentPlaceCount { get; set; }
        public float PlacePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Places Places { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
